version: '3'
volumes:
  ssh_key:

services:
  python3:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'exp'
    working_dir: '/usr/src/app'
    tty: true
    volumes:
      - ../app:/usr/src/app
      - ssh_key:/usr/src/app/.ssh